CREATE TABLE `haitiTbl` (
  `id` int(5) NOT NULL auto_increment,
  `link` varchar(100) NOT NULL,
  `caption` varchar(300) NOT NULL,
  `alt` varchar(100) NOT NULL,
  `css_class` varchar(25) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `link` (`link`),
  KEY `caption` (`caption`),
  KEY `alt` (`alt`),
  KEY `css_class` (`css_class`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `haitiTbl` (link, caption, alt) VALUES 
('/travel-photos/images-haiti/pre-earthquake-haiti-champs-de-mars-ginette-sylvain-tap-tap.jpg', 'Ginette Sylvain at Champs de Mars waiting next to a tap tap.', 'Ginette Sylvain at Champs de Mars waiting next to a tap tap pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-champs-de-mars-haiti-concert-choir.jpg', 'A gospel choir sings at Champs de Mars. There were several other bands performing that night.', 'A gospel choir sings at Champs de Mars pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-champs-de-mars-haiti-guitarist.jpg', 'A man playing an accoustic guitar, solo, draws a crowd.', 'A man playing an accoustic guitar, solo, draws a crowd pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-champs-de-mars-haiti-presidential-palace.jpg', 'The presidential palace decorated for Christmas in December, 2002.', 'The presidential palace decorated for Christmas in December, 2002 pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-djouvensong-sylvain-IMGA0256.jpg', 'Djouvensong Sylvain preparing to drive me to the airport.', 'Djouvensong Sylvain preparing to drive me to the airport pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-ginette-sylvain-figure.jpg', 'Beautiful photo of Ginette Sylvain in her youth.', 'Beautiful photo of Ginette Sylvain in her youth pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-ginette-sylvain-head.jpg', 'Beautiful photo of Ginette Sylvain in her youth, close-up.' 'Beautiful photo of Ginette Sylvain in her youth, close-up pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-ginette-sylvain-wedding-bride.jpg', 'Ginette Sylvain on her wedding night.', 'Ginette Sylvain on her wedding night pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-church-sunday-IMGA0257.jpg', 'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.', 'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel. pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-church-sunday-IMGA0258.jpg', 'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-church-sunday-IMGA0260.jpg', 'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-church-sunday-IMGA0261.jpg', 'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-church-sunday-ginette-sylvain-IMGA0259.jpg', 'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-ginette-sylvain-IMGA0262.jpg', 'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0266.jpg', 'Ginette on the Balcony of Detente Tropical Hotel in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0267.jpg', 'Ginette and her then husband at Detente Tropicale Hotel in La Plaine, Haiti.',

('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0268.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0269.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0270.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0271.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0273.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0274.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0284.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0285.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0309.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0310.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')

('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0311.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0314.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0315.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0316.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0317.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0318.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0319.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-IMGA0320.jpg', 'Village life in La Plaine, Haiti.', 'Village life in La Plaine, Haiti pre earthquake haiti')

('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0071.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0072.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0073.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0074.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0075.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0076.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0077.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0078.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0079.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0080.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0081.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0082.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0102.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0103.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0104.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0105.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0106.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0107.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-IMGA0109.jpg', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti pre earthquake haiti')

('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-callus-removal-IMGA0101.jpg', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti. pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-callus-removal-IMGA0108.jpg', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti. pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-callus-removal-IMGA0110.jpg', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti. pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-callus-removal-IMGA0111.jpg', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti. pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-callus-removal-IMGA0112.jpg', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti. pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-callus-removal-IMGA0113.jpg', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti. pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-callus-removal-IMGA0114.jpg', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti. pre earthquake haiti'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-balcony-detente-tropicale-hotel-callus-removal.jpg', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti. pre earthquake haiti')

('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-buying-bread-IMGA0286.jpg', 'Buying morning bread in La Plaine, Haiti. Bread vendors in the village travel from street to street and house to house.', 'Buying morning bread in La Plaine, Haiti. Bread vendors in the village travel from street to street and house to house.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-buying-bread-IMGA0287.jpg', 'Buying morning bread in La Plaine, Haiti. Bread vendors in the village travel from street to street and house to house.', 'Buying morning bread in La Plaine, Haiti. Bread vendors in the village travel from street to street and house to house.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0165.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0166.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0167.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0169.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0170.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0171.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0182.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0184.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.')

('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-IMGA0288.jpg', 'This young boy in La Plaine, Haiti was deaf and could not speak. He was always happy. Saw him several times and was always smiling.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-infants-at-home.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-children-school-girls.jpg', 'The children of La Plaine, Haiti.', 'The children of La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-detente-tropicale-hotel-ginette-sylvain-IMGA0263.jpg', 'Ginette Sylvain poses on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette Sylvain poses on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-detente-tropicale-hotel-ginette-sylvain-IMGA0264.jpg', 'Ginette Sylvain poses on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.', 'Ginette Sylvain poses on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouvensong-sylvain-IMGA0157.jpg', 'Ginettes brother Djouvensong, poses for the camera (2003).', 'Ginettes brother Djouvensong, poses for the camera (2003).'),
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouvensongs-car-IMGA0168.jpg', 'Djouvensongs car in La Plaine, Haiti.', 'Djouvensongs car in La Plaine, Haiti.')

('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouvensongs-car-IMGA0173.jpg', 'Boss works on Djouvensongs car in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouvensongs-car-IMGA0174.jpg', 'Boss speaks with Ginettes late father, Msr. Sylvain.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouvensongs-car-IMGA0175.jpg', 'Boss works on Djouvensongs car in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouvensongs-car-IMGA0176.jpg', 'Boss works on Djouvensongs car in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouvensongs-car-IMGA0177.jpg', 'Boss works on Djouvensongs car in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouvensongs-car-IMGA0178.jpg', 'Boss works on Djouvensongs car in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-djouverlie-sylvain-IMGA0321.jpg', 'Djouvensongs daughter, Djouverlie. In this photo (2004) she was 3 years old.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-flowers-IMGA0289.jpg', 'Beautiful flowers in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-flowers-IMGA0290.jpg', 'Beautiful flowers in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-flowers-IMGA0291.jpg', 'Beautiful flowers in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-flowers-IMGA0292.jpg', 'Beautiful flowers in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-flowers-IMGA0293.jpg', 'Beautiful flowers in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-flowers-IMGA0303.jpg', 'Beautiful flowers in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-ginette-sylvain-IMGA0275.jpg', 'Ginette Sylvain brushing her hair in the morning in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-ginette-sylvain-IMGA0276.jpg', 'Ginette Sylvain brushing her hair in the morning in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-ginette-sylvain-detente-tropicale-hotel.jpg', 'Ginette Sylvain and her ex husband on the balcony of Detente Tropicale Hotel in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-ginette-sylvain-gets-shoe-shine.jpg', 'Ginette Sylvain getting a shoe shine in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-ginette-sylvain-new-hairstyle-IMGA0156.jpg', 'Ginette Sylvain straight from a beauty salon in the village with a new hairstyle in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-ginette-sylvain-wedding-IMGA0099.jpg', 'Ginette Sylvains wedding, December 2002 in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-ginette-sylvain-wedding-IMGA0100.jpg', 'Ginette Sylvain on her wedding day in December 2002 in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-haitian-christian-center-for-the-deaf-IMGA0296.jpg', 'The road to the Haitian Christian Center for the Deaf in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-haitian-christian-center-for-the-deaf-palm-tree-IMGA0298.jpg', 'Palm tree at the Haitian Christian Center for the Deaf in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-haitian-family-IMGA0158.jpg', 'Friends of Ginette Sylvain in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-haitian-family-IMGA0159.jpg', 'Friends of Ginette Sylvain in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-haitian-family-IMGA0160.jpg', 'Friends of Ginette Sylvain in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-haitian-iron-clothes-IMGA0180.jpg', 'Using a Haitian iron requires hot charcoal in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-haitian-iron-clothes-IMGA0181.jpg', 'Using a Haitian iron requires hot charcoal in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-killing-pig-IMGA0068.jpg', 'Young man kills a pig in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-killing-pig-IMGA0069.jpg', 'Young man kills a pig in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-killing-pig-IMGA0070.jpg', 'Young man kills a pig in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-killing-pig-IMGA0083.jpg', 'Young man kills a pig in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-killing-pig-IMGA0084.jpg', 'Young man kills a pig in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-market-2.jpg', 'Haitian market.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-market.jpg', 'Haitian market.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-mountains-IMGA0161.jpg', 'Mountains as seen from La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-mountains-IMGA0162.jpg', 'Mountains as seen from La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-mountains-IMGA0163.jpg', 'Mountains as seen from La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-palm-tree-IMGA0097.jpg', 'Palm tree in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-pedestrians.jpg', 'Pedestrians in La Plaine, Haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-pepes-wife-ginette-sylvain.jpg', 'Ginette with Pepes wife.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-plants-IMGA0306.jpg', 'Plants in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-plants-IMGA0307.jpg', 'Plants in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-quiet-streets-IMGA0152.jpg', 'Quiet streets in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-quiet-streets-IMGA0153.jpg', 'Quiet streets in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-quiet-streets-IMGA0154.jpg', 'Quiet streets in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-quiet-streets-IMGA0155.jpg', 'Quiet streets in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-quiet-village-2.jpg', 'Quiet village in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-quiet-village.jpg', 'Quiet village in La Plaine, Haiti.',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-red-flowers-IMGA0094.jpg', 'Red flowers in La Plaine, Haiti.', 'Red flowers in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-red-flowers-IMGA0095.jpg', 'Red flowers in La Plaine, Haiti.', 'Red flowers in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-red-flowers-IMGA0096.jpg', 'Red flowers in La Plaine, Haiti.', 'Red flowers in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-red-flowers-IMGA0098.jpg', 'Red flowers in La Plaine, Haiti.', 'Red flowers in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-route-nationale-1-truck-crash-1.jpg', 'Truck crash on Route Nationale 1.', 'Truck crash on Route Nationale 1  pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-route-nationale-1-truck-crash-2.jpg', 'Truck crash on Route Nationale 1.', 'Truck crash on Route Nationale 1  pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-satellite-disk-IMGA0179.jpg', 'Haitian satellite dish in La Plaine, 2004', 'Haitian satellite dish in La Plaine, 2004  pre earthquake haiti', 
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-sign-painter-IMGA0164.jpg', 'Haitian sign painter', 'Haitian sign painter pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-sylvain-family-friend-IMGA0085.jpg', 'Sylvain family neighbor', 'Sylvain family neighbor pre earthquake haiti', 
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-sylvain-family-friend-IMGA0326.jpg', 'Sylvain family neighbor', 'Sylvain family neighbor pre earthquake haiti', 
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-sylvain-family-neighbor-IMGA0172.jpg', 'Sylvain family neighbor', 'Sylvain family neighbor pre earthquake haiti', 
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-sylvain-family-neighbors-IMGA0183.jpg', 'Sylvain family neighbor', 'Sylvain family neighbor pre earthquake haiti', 
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-sylvain-home-IMGA0272.jpg', 'Sylvain family house in La Plaine, Haiti', 'Sylvain family house in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-tap-tap.jpg', 'Tap tap in La Plaine, Haiti', 'Tap tap in La Plaine, Haiti pre earthquake haiti', 
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0277.jpg', 'Trees in La Plaine, Haiti', 'Trees in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0278.jpg', 'Trees in La Plaine, Haiti', 'Trees in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0279.jpg', 'Trees in La Plaine, Haiti', 'Trees in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0280.jpg', 'Trees in La Plaine, Haiti', 'Trees in La Plaine, Haiti pre earthquake haiti',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0281.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0282.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0283.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0294.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0295.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0297.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0305.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0308.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0312.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0313.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0322.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0323.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0324.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-IMGA0325.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-trees-palm-tree-IMGA0299.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-water-ice-vendor.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-weaver-birds-nests-IMGA0300.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-weaver-birds-nests-IMGA0301.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-weaver-birds-nests-IMGA0302.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-weaver-birds-nests-IMGA0304.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-woodworker-IMGA0149.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-woodworker-IMGA0150.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-haiti-woodworker-IMGA0151.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-la-plaine-patrick-sylvain-IMGA0255.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-luly-haiti-girl-with-her-donkey.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0185.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0186.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0187.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0188.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0189.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0190.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0191.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0192.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0193.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0194.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0195.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0196.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0197.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0198.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0199.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0200.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0201.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0202.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0203.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0204.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0205.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0206.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0207.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0208.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0209.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0210.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0211.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0212.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0213.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0214.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0215.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0216.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0217.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0218.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0219.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0220.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0221.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0222.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0223.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0224.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0225.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0226.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0227.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0228.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0229.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0230.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0231.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0232.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0233.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0234.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0235.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0236.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0237.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0238.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0239.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0240.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0241.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0242.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0243.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0244.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0245.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0246.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0247.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0248.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-IMGA0249.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-gayelle-ginette-sylvain-pepe-wife-IMGA0251.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-gayelle-ginette-sylvain-pepe-wife-IMGA0251a.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-gayelle-sylvain-IMGA0250.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-gayelle-sylvain-ginette-sylvain-IMGA0253.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-ginette-gayelle-sylvain.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-ginette-sylvain-IMGA0252.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-petionville-pepe-pigs-IMGA0254.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-armed-guard-texaco-station.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-armed-guards.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-bridge.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-commuters.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-downtown-IMGA0086.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-downtown-IMGA0087.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-downtown-IMGA0088.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-downtown-IMGA0089.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-downtown-IMGA0090.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-downtown-IMGA0091.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-downtown-IMGA0092.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-downtown-IMGA0093.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-port-au-prince-haiti-people-working.jpg',
('/travel-photos/images-haiti/pre-earthquake-haiti-sisters-ginette-gayelle-sylvain.jpg',