<?php
$captionarray = array(
'Ginette Sylvain at Champs de Mars waiting next to a tap tap.',
'A gospel choir sings at Champs de Mars. There were several other bands performing that night.',
'A man playing an accoustic guitar, solo, draws a crowd.',
'The presidential palace decorated for Christmas in December, 2002.',
'Djouvensong Sylvain preparing to drive me to the airport.',
'Beautiful photo of Ginette Sylvain in her youth.',
'Beautiful photo of Ginette Sylvain in her youth, close-up.',
'Ginette Sylvain on her wedding night.',
'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Ginette on the Balcony of Detente Tropical Hotel in La Plaine, Haiti.',
'Ginette and her then husband at Detente Tropicale Hotel in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'Village life in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Buying morning bread in La Plaine, Haiti. Bread vendors in the village travel from street to street and house to house.',
'Buying morning bread in La Plaine, Haiti. Bread vendors in the village travel from street to street and house to house.',
'The children of La Plaine, Haiti.',
'The children of La Plaine, Haiti.',
'The children of La Plaine, Haiti.',
'The children of La Plaine, Haiti.',
'The children of La Plaine, Haiti.',
'The children of La Plaine, Haiti.',
'The children of La Plaine, Haiti.',
'The children of La Plaine, Haiti.',
'This young boy in La Plaine, Haiti was deaf and could not speak. He was always happy. Saw him several times and was always smiling.',
'The children of La Plaine, Haiti.',
'The children of La Plaine, Haiti.',
'Ginette Sylvain poses on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette Sylvain poses on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginettes brother Djouvensong, poses for the camera (2003).',
'Djouvensongs car in La Plaine, Haiti.',
'Boss works on Djouvensongs car in La Plaine, Haiti.',
'Boss speaks with Ginettes late father.',
'Boss works on Djouvensongs car in La Plaine, Haiti.',
'Boss works on Djouvensongs car in La Plaine, Haiti.',
'Boss works on Djouvensongs car in La Plaine, Haiti.',
'Boss works on Djouvensongs car in La Plaine, Haiti.',
'Djouvensongs daughter, Djouverlie. In this photo (2004) she was 3 years old.',
'Beautiful flowers in La Plaine, Haiti.',
'Beautiful flowers in La Plaine, Haiti.',
'Beautiful flowers in La Plaine, Haiti.',
'Beautiful flowers in La Plaine, Haiti.',
'Beautiful flowers in La Plaine, Haiti.',
'Beautiful flowers in La Plaine, Haiti.',
'Ginette Sylvain brushing her hair in the morning in La Plaine, Haiti.',
'Ginette Sylvain brushing her hair in the morning in La Plaine, Haiti.',
'Ginette Sylvain and her ex husband on the balcony of Detente Tropicale Hotel in La Plaine, Haiti.',
'Ginette Sylvain getting a shoe shine in La Plaine, Haiti.',
'Ginette Sylvain straight from a beauty salon in the village with a new hairstyle in La Plaine, Haiti.',
'Ginette Sylvains wedding, December 2002 in La Plaine, Haiti.',
'Ginette Sylvain on her wedding day in December 2002 in La Plaine, Haiti.',
'The road to the Haitian Christian Center for the Deaf in La Plaine, Haiti.',
'Palm tree at the Haitian Christian Center for the Deaf in La Plaine, Haiti.',
'Friends of Ginette Sylvain in La Plaine, Haiti.',
'Friends of Ginette Sylvain in La Plaine, Haiti.',
'Friends of Ginette Sylvain in La Plaine, Haiti.',
'Using a Haitian iron requires hot charcoal in La Plaine, Haiti.',
'Using a Haitian iron requires hot charcoal in La Plaine, Haiti.',
'Young man kills a pig in La Plaine, Haiti.',
'Young man kills a pig in La Plaine, Haiti.',
'Young man kills a pig in La Plaine, Haiti.',
);

?>